window.SURVEY_CONFIG = {
  BACKEND_BASE_URL: "",
  AI_ENDPOINT: "",
  OPENAI_API_KEY: "",
  OPENAI_MODEL: "gpt-4o-mini",
  NOTIFICATION_WEBHOOK_URL: "",
  GOOGLE_DOC_WEBHOOK_URL: "",
  BUDGET_SHEET_URL: ""
};
